name: bhw_app
description: A new Flutter project.

publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.0.5
  font_awesome_flutter: ^10.6.0
  quickalert: ^1.0.2
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.3.13
  localstore: ^1.3.5

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  image: assets/icon/icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/img/bg-min.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/Poppins-ExtraBold.ttf
  #         weight: 800
  #       - asset: assets/fonts/Poppins-Black.ttf
  #         weight: 900
